[build]
command = "npx webpack --mode production"
publish = "dist"
package = "."

[functions]
external_node_modules = ["firebase"]

[build.environment]
NODE_ENV = "production"

[build.processing]
[build.processing.javascript]
esbuild = true 