   [build]
   command = "npm install webpack@5.95.0 && npx webpack"
   publish = "dist" 

   [functions]
   external_node_modules = ["firebase"]

   [build.environment]
   NODE_ENV = "production"

   [build.processing]
   [build.processing.javascript]
   esbuild = true 